export const PROFESSOR_LIST_REQUESTED = "PROFESSOR_LIST_REQUESTED";
export const PROFESSOR_LIST_SUCCEEDED = "PROFESSOR_LIST_SUCCEEDED";
export const PROFESSOR_LIST_FAILED = "PROFESSOR_LIST_FAILED";
export const PROFESSOR_REQUEST = "PROFESSOR_REQUEST";
export const PROFESSOR_SUCCESS = "PROFESSOR_SUCCESS";
export const PROFESSOR_FAIL = "PROFESSOR_FAIL";